function result = exn_thrower()

error('I take exception to everything.');

end

